name: fury_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

resolution: workspace

# Add regular dependencies here.
dependencies:
  fury_core: 1.0.0

  build_runner_core: any
  source_gen: any
  build_runner: any
dev_dependencies:
  lints: ^5.0.0
  build: ^2.4.2
  test: ^1.24.0
  checks: ^0.3.0
  build_test: ^2.2.3
  analyzer: ^7.3.0
  collection: ^1.19.1
