name: dart_fury
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  fury_core: any
  build_runner: ^2.4.13

  build_runner_core: any
  source_gen: any
  build_resolvers: any
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

workspace:
  - packages/fury-core
  # - packages/fury-gen
  - packages/fury-test
