name: fury
description: apache fury dart support
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  analyzer: '>=6.5.0 <8.0.0'
  build: ^2.4.1
  build_config: ^1.1.0
  collection: ^1.19.1
  meta: ^1.14.0
  source_gen: ^2.0.0
  glob: ^2.1.3
  decimal: ^3.2.1

dev_dependencies:
  lints: ^5.0.0
