included:
  - Sources
  - Tests
  - Package.swift

excluded:
  - .build

identifier_name:
  min_length:
    warning: 2
    error: 1

line_length:
  warning: 160
  error: 200
  ignores_comments: true

function_body_length:
  warning: 200
  error: 260

type_body_length:
  warning: 900
  error: 1400

file_length:
  warning: 1900
  error: 2200

cyclomatic_complexity:
  warning: 50
  error: 70
