// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

use fory::{Fory, ForyObject};
use std::sync::OnceLock;

// Type ID 1471345060 is generated from auto_id.Wrapper
#[derive(ForyObject, Debug, Clone, PartialEq)]
pub enum Wrapper {
    #[fory(id = 1)]
    Envelope(Envelope),
    #[fory(id = 2)]
    Raw(String),
}

impl Default for Wrapper {
    fn default() -> Self {
        Self::Envelope(Default::default())
    }
}

impl Wrapper {
    pub fn to_bytes(&self) -> Result<Vec<u8>, fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> Result<Wrapper, fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

pub mod envelope {
    use super::*;

    // Type ID 1609214087 is generated from auto_id.Envelope.Detail
    #[derive(ForyObject, Debug, Clone, PartialEq)]
    pub enum Detail {
        #[fory(id = 1)]
        Payload(envelope::Payload),
        #[fory(id = 2)]
        Note(String),
    }

    impl Default for Detail {
        fn default() -> Self {
            Self::Payload(Default::default())
        }
    }

    impl Detail {
        pub fn to_bytes(&self) -> Result<Vec<u8>, fory::Error> {
            let fory = detail::get_fory();
            fory.serialize(self)
        }

        pub fn from_bytes(data: &[u8]) -> Result<Detail, fory::Error> {
            let fory = detail::get_fory();
            fory.deserialize(data)
        }
    }

    // Type ID 715094189 is generated from auto_id.Envelope.Payload
    #[derive(ForyObject, Debug, Clone, PartialEq, Default)]
    pub struct Payload {
        #[fory(id = 1)]
        pub value: i32,
    }

    impl Payload {
        pub fn to_bytes(&self) -> Result<Vec<u8>, fory::Error> {
            let fory = detail::get_fory();
            fory.serialize(self)
        }

        pub fn from_bytes(data: &[u8]) -> Result<Payload, fory::Error> {
            let fory = detail::get_fory();
            fory.deserialize(data)
        }
    }
}

// Type ID 874961588 is generated from auto_id.Envelope
#[derive(ForyObject, Debug, Clone, PartialEq, Default)]
pub struct Envelope {
    #[fory(id = 1)]
    pub id: String,
    #[fory(id = 2, nullable = true)]
    pub payload: Option<envelope::Payload>,
    #[fory(id = 3, type_id = "union")]
    pub detail: envelope::Detail,
}

impl Envelope {
    pub fn to_bytes(&self) -> Result<Vec<u8>, fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> Result<Envelope, fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

pub fn register_types(fory: &mut Fory) -> Result<(), fory::Error> {
    fory.register_union::<Wrapper>(1471345060)?;
    fory.register_union::<envelope::Detail>(1609214087)?;
    fory.register::<envelope::Payload>(715094189)?;
    fory.register::<Envelope>(874961588)?;
    Ok(())
}

mod detail {
    use super::*;

    pub(super) fn get_fory() -> &'static Fory {
        static FORY: OnceLock<Fory> = OnceLock::new();
        FORY.get_or_init(|| {
            let mut fory = Fory::default()
                .xlang(true)
                .track_ref(true)
                .compatible(true);
            register_types(&mut fory).expect("failed to register fory types");
            fory
        })
    }
}
