// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Tests for the `#[fory(skip_default)]` attribute.
//!
//! This attribute prevents `ForyObject` from generating a `Default` implementation,
//! which is useful when you have a manual `impl Default` for your type.

use fory_core::fory::Fory;
use fory_derive::ForyObject;

/// Test struct with manual Default implementation.
/// Using `#[fory(skip_default)]` to prevent ForyObject from generating Default.
#[derive(ForyObject, Debug, PartialEq)]
#[fory(skip_default)]
struct NodeWithCustomDefault {
    addr: String,
}

impl Default for NodeWithCustomDefault {
    fn default() -> Self {
        Self {
            addr: "localhost:8080".to_string(),
        }
    }
}

#[test]
fn test_skip_default_struct() {
    let mut fory = Fory::default();
    fory.register::<NodeWithCustomDefault>(1).unwrap();

    let node = NodeWithCustomDefault {
        addr: "192.168.1.1:3000".to_string(),
    };

    let bytes = fory.serialize(&node).unwrap();
    let decoded: NodeWithCustomDefault = fory.deserialize(&bytes).unwrap();
    assert_eq!(node, decoded);
}

#[test]
fn test_skip_default_uses_custom_default() {
    // Verify that our custom Default implementation is used
    let node = NodeWithCustomDefault::default();
    assert_eq!(node.addr, "localhost:8080");

    // Verify ForyDefault also uses the custom Default
    use fory_core::ForyDefault;
    let node2 = NodeWithCustomDefault::fory_default();
    assert_eq!(node2.addr, "localhost:8080");
}

/// Test enum with manual Default implementation.
#[derive(ForyObject, Debug, PartialEq)]
#[fory(skip_default)]
enum StatusWithCustomDefault {
    Active,
    Inactive,
    Pending,
}

// Allow derivable_impls because we're specifically testing manual Default impl with skip_default
#[allow(clippy::derivable_impls)]
impl Default for StatusWithCustomDefault {
    fn default() -> Self {
        // Custom default: Pending instead of Active (first variant)
        StatusWithCustomDefault::Pending
    }
}

#[test]
fn test_skip_default_enum() {
    let mut fory = Fory::default();
    fory.register::<StatusWithCustomDefault>(2).unwrap();

    let status = StatusWithCustomDefault::Active;
    let bytes = fory.serialize(&status).unwrap();
    let decoded: StatusWithCustomDefault = fory.deserialize(&bytes).unwrap();
    assert_eq!(status, decoded);
}

#[test]
fn test_skip_default_enum_uses_custom_default() {
    // Verify that our custom Default implementation is used
    let status = StatusWithCustomDefault::default();
    assert_eq!(status, StatusWithCustomDefault::Pending);

    // Verify ForyDefault also uses the custom Default
    use fory_core::ForyDefault;
    let status2 = StatusWithCustomDefault::fory_default();
    assert_eq!(status2, StatusWithCustomDefault::Pending);
}

/// Test that skip_default = false works (same as not specifying)
#[derive(ForyObject, Debug, PartialEq)]
#[fory(skip_default = false)]
struct NormalStruct {
    value: i32,
}

#[test]
fn test_skip_default_false() {
    let mut fory = Fory::default();
    fory.register::<NormalStruct>(3).unwrap();

    let data = NormalStruct { value: 42 };
    let bytes = fory.serialize(&data).unwrap();
    let decoded: NormalStruct = fory.deserialize(&bytes).unwrap();
    assert_eq!(data, decoded);

    // Default should work (generated by ForyObject)
    let default_data = NormalStruct::default();
    assert_eq!(default_data.value, 0);
}
